/**
 * Code-generates `src/services/prompts/_generated.ts` from the `.md` files
 * under `prompts/classifier/`. Cloudflare Workers has no `fs`, so the prompt
 * has to ship inside the Worker bundle as a string constant; this script is
 * the single, deterministic step that turns the `.md` source-of-truth into
 * that constant.
 *
 * Run after editing any `prompts/classifier/*.md` (or whenever
 * `_generated.ts` falls behind in CI):
 *
 *     pnpm tsx scripts/embed-prompts.ts
 *
 * The generated file is committed — Workers builds (`wrangler dev`,
 * `wrangler deploy`) consume it as a normal TypeScript module.
 */

import { readFileSync, readdirSync, writeFileSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const REPO_ROOT = join(dirname(fileURLToPath(import.meta.url)), "..");
const CLASSIFIER_DIR = join(REPO_ROOT, "prompts", "classifier");
const OUT_PATH = join(REPO_ROOT, "src", "services", "prompts", "_generated.ts");

function stripFrontmatter(s: string): string {
  if (!s.startsWith("---\n")) return s;
  const end = s.indexOf("\n---\n", 4);
  return end === -1 ? s : s.slice(end + 5);
}

function loadClassifierBodies(): Map<string, string> {
  const bodies = new Map<string, string>();
  for (const name of readdirSync(CLASSIFIER_DIR).sort()) {
    const m = name.match(/^system\.(v\d+)\.md$/);
    if (!m) continue;
    const version = m[1]!;
    const raw = readFileSync(join(CLASSIFIER_DIR, name), "utf8");
    bodies.set(version, stripFrontmatter(raw).replace(/\s+$/, ""));
  }
  if (bodies.size === 0) {
    throw new Error(`no system.vN.md files found under ${CLASSIFIER_DIR}`);
  }
  return bodies;
}

function emit(bodies: Map<string, string>): string {
  const versions = [...bodies.keys()].sort();
  const lines: string[] = [];
  lines.push(`// AUTO-GENERATED by scripts/embed-prompts.ts — do not edit.`);
  lines.push(`// Source: prompts/classifier/system.{${versions.join(",")}}.md`);
  lines.push(`// Run \`pnpm tsx scripts/embed-prompts.ts\` after editing any source.`);
  lines.push("");
  lines.push(`export const CLASSIFIER_SYSTEM_PROMPTS = {`);
  for (const v of versions) {
    const body = bodies.get(v)!;
    // String.raw + backtick template would still need backtick escapes;
    // emit JSON.stringify form (one line) so escapes are bullet-proof.
    lines.push(`  ${v}: ${JSON.stringify(body)},`);
  }
  lines.push(`} as const;`);
  lines.push("");
  lines.push(`export type GeneratedClassifierPromptVersion = keyof typeof CLASSIFIER_SYSTEM_PROMPTS;`);
  lines.push("");
  return lines.join("\n");
}

const bodies = loadClassifierBodies();
const out = emit(bodies);
writeFileSync(OUT_PATH, out, "utf8");
console.log(
  `wrote ${OUT_PATH} — ${bodies.size} versions: ${[...bodies.keys()].join(", ")}`,
);
